spring:
  datasource:
    url: jdbc:mysql://localhost:3306/egsboot?characterEncoding=utf8&serverTimezone=UTC
    username: egsboot
    password: Aa123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
egs:
  dbtype: mysql

